# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.12

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/cmake/bin/cmake

# The command to remove a file.
RM = /opt/cmake/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/saishi/Desktop/WORKING/Git/PASTML

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/saishi/Desktop/WORKING/Git/PASTML

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/opt/cmake/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/opt/cmake/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/saishi/Desktop/WORKING/Git/PASTML/CMakeFiles /home/saishi/Desktop/WORKING/Git/PASTML/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/saishi/Desktop/WORKING/Git/PASTML/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named pastml

# Build rule for target.
pastml: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 pastml
.PHONY : pastml

# fast build rule for target.
pastml/fast:
	$(MAKE) -f CMakeFiles/pastml.dir/build.make CMakeFiles/pastml.dir/build
.PHONY : pastml/fast

likelihood.o: likelihood.c.o

.PHONY : likelihood.o

# target to build an object file
likelihood.c.o:
	$(MAKE) -f CMakeFiles/pastml.dir/build.make CMakeFiles/pastml.dir/likelihood.c.o
.PHONY : likelihood.c.o

likelihood.i: likelihood.c.i

.PHONY : likelihood.i

# target to preprocess a source file
likelihood.c.i:
	$(MAKE) -f CMakeFiles/pastml.dir/build.make CMakeFiles/pastml.dir/likelihood.c.i
.PHONY : likelihood.c.i

likelihood.s: likelihood.c.s

.PHONY : likelihood.s

# target to generate assembly for a file
likelihood.c.s:
	$(MAKE) -f CMakeFiles/pastml.dir/build.make CMakeFiles/pastml.dir/likelihood.c.s
.PHONY : likelihood.c.s

logger.o: logger.c.o

.PHONY : logger.o

# target to build an object file
logger.c.o:
	$(MAKE) -f CMakeFiles/pastml.dir/build.make CMakeFiles/pastml.dir/logger.c.o
.PHONY : logger.c.o

logger.i: logger.c.i

.PHONY : logger.i

# target to preprocess a source file
logger.c.i:
	$(MAKE) -f CMakeFiles/pastml.dir/build.make CMakeFiles/pastml.dir/logger.c.i
.PHONY : logger.c.i

logger.s: logger.c.s

.PHONY : logger.s

# target to generate assembly for a file
logger.c.s:
	$(MAKE) -f CMakeFiles/pastml.dir/build.make CMakeFiles/pastml.dir/logger.c.s
.PHONY : logger.c.s

main.o: main.c.o

.PHONY : main.o

# target to build an object file
main.c.o:
	$(MAKE) -f CMakeFiles/pastml.dir/build.make CMakeFiles/pastml.dir/main.c.o
.PHONY : main.c.o

main.i: main.c.i

.PHONY : main.i

# target to preprocess a source file
main.c.i:
	$(MAKE) -f CMakeFiles/pastml.dir/build.make CMakeFiles/pastml.dir/main.c.i
.PHONY : main.c.i

main.s: main.c.s

.PHONY : main.s

# target to generate assembly for a file
main.c.s:
	$(MAKE) -f CMakeFiles/pastml.dir/build.make CMakeFiles/pastml.dir/main.c.s
.PHONY : main.c.s

marginal_approximation.o: marginal_approximation.c.o

.PHONY : marginal_approximation.o

# target to build an object file
marginal_approximation.c.o:
	$(MAKE) -f CMakeFiles/pastml.dir/build.make CMakeFiles/pastml.dir/marginal_approximation.c.o
.PHONY : marginal_approximation.c.o

marginal_approximation.i: marginal_approximation.c.i

.PHONY : marginal_approximation.i

# target to preprocess a source file
marginal_approximation.c.i:
	$(MAKE) -f CMakeFiles/pastml.dir/build.make CMakeFiles/pastml.dir/marginal_approximation.c.i
.PHONY : marginal_approximation.c.i

marginal_approximation.s: marginal_approximation.c.s

.PHONY : marginal_approximation.s

# target to generate assembly for a file
marginal_approximation.c.s:
	$(MAKE) -f CMakeFiles/pastml.dir/build.make CMakeFiles/pastml.dir/marginal_approximation.c.s
.PHONY : marginal_approximation.c.s

marginal_likelihood.o: marginal_likelihood.c.o

.PHONY : marginal_likelihood.o

# target to build an object file
marginal_likelihood.c.o:
	$(MAKE) -f CMakeFiles/pastml.dir/build.make CMakeFiles/pastml.dir/marginal_likelihood.c.o
.PHONY : marginal_likelihood.c.o

marginal_likelihood.i: marginal_likelihood.c.i

.PHONY : marginal_likelihood.i

# target to preprocess a source file
marginal_likelihood.c.i:
	$(MAKE) -f CMakeFiles/pastml.dir/build.make CMakeFiles/pastml.dir/marginal_likelihood.c.i
.PHONY : marginal_likelihood.c.i

marginal_likelihood.s: marginal_likelihood.c.s

.PHONY : marginal_likelihood.s

# target to generate assembly for a file
marginal_likelihood.c.s:
	$(MAKE) -f CMakeFiles/pastml.dir/build.make CMakeFiles/pastml.dir/marginal_likelihood.c.s
.PHONY : marginal_likelihood.c.s

param_minimization.o: param_minimization.c.o

.PHONY : param_minimization.o

# target to build an object file
param_minimization.c.o:
	$(MAKE) -f CMakeFiles/pastml.dir/build.make CMakeFiles/pastml.dir/param_minimization.c.o
.PHONY : param_minimization.c.o

param_minimization.i: param_minimization.c.i

.PHONY : param_minimization.i

# target to preprocess a source file
param_minimization.c.i:
	$(MAKE) -f CMakeFiles/pastml.dir/build.make CMakeFiles/pastml.dir/param_minimization.c.i
.PHONY : param_minimization.c.i

param_minimization.s: param_minimization.c.s

.PHONY : param_minimization.s

# target to generate assembly for a file
param_minimization.c.s:
	$(MAKE) -f CMakeFiles/pastml.dir/build.make CMakeFiles/pastml.dir/param_minimization.c.s
.PHONY : param_minimization.c.s

parsimony.o: parsimony.c.o

.PHONY : parsimony.o

# target to build an object file
parsimony.c.o:
	$(MAKE) -f CMakeFiles/pastml.dir/build.make CMakeFiles/pastml.dir/parsimony.c.o
.PHONY : parsimony.c.o

parsimony.i: parsimony.c.i

.PHONY : parsimony.i

# target to preprocess a source file
parsimony.c.i:
	$(MAKE) -f CMakeFiles/pastml.dir/build.make CMakeFiles/pastml.dir/parsimony.c.i
.PHONY : parsimony.c.i

parsimony.s: parsimony.c.s

.PHONY : parsimony.s

# target to generate assembly for a file
parsimony.c.s:
	$(MAKE) -f CMakeFiles/pastml.dir/build.make CMakeFiles/pastml.dir/parsimony.c.s
.PHONY : parsimony.c.s

runpastml.o: runpastml.c.o

.PHONY : runpastml.o

# target to build an object file
runpastml.c.o:
	$(MAKE) -f CMakeFiles/pastml.dir/build.make CMakeFiles/pastml.dir/runpastml.c.o
.PHONY : runpastml.c.o

runpastml.i: runpastml.c.i

.PHONY : runpastml.i

# target to preprocess a source file
runpastml.c.i:
	$(MAKE) -f CMakeFiles/pastml.dir/build.make CMakeFiles/pastml.dir/runpastml.c.i
.PHONY : runpastml.c.i

runpastml.s: runpastml.c.s

.PHONY : runpastml.s

# target to generate assembly for a file
runpastml.c.s:
	$(MAKE) -f CMakeFiles/pastml.dir/build.make CMakeFiles/pastml.dir/runpastml.c.s
.PHONY : runpastml.c.s

scaling.o: scaling.c.o

.PHONY : scaling.o

# target to build an object file
scaling.c.o:
	$(MAKE) -f CMakeFiles/pastml.dir/build.make CMakeFiles/pastml.dir/scaling.c.o
.PHONY : scaling.c.o

scaling.i: scaling.c.i

.PHONY : scaling.i

# target to preprocess a source file
scaling.c.i:
	$(MAKE) -f CMakeFiles/pastml.dir/build.make CMakeFiles/pastml.dir/scaling.c.i
.PHONY : scaling.c.i

scaling.s: scaling.c.s

.PHONY : scaling.s

# target to generate assembly for a file
scaling.c.s:
	$(MAKE) -f CMakeFiles/pastml.dir/build.make CMakeFiles/pastml.dir/scaling.c.s
.PHONY : scaling.c.s

states.o: states.c.o

.PHONY : states.o

# target to build an object file
states.c.o:
	$(MAKE) -f CMakeFiles/pastml.dir/build.make CMakeFiles/pastml.dir/states.c.o
.PHONY : states.c.o

states.i: states.c.i

.PHONY : states.i

# target to preprocess a source file
states.c.i:
	$(MAKE) -f CMakeFiles/pastml.dir/build.make CMakeFiles/pastml.dir/states.c.i
.PHONY : states.c.i

states.s: states.c.s

.PHONY : states.s

# target to generate assembly for a file
states.c.s:
	$(MAKE) -f CMakeFiles/pastml.dir/build.make CMakeFiles/pastml.dir/states.c.s
.PHONY : states.c.s

tree.o: tree.c.o

.PHONY : tree.o

# target to build an object file
tree.c.o:
	$(MAKE) -f CMakeFiles/pastml.dir/build.make CMakeFiles/pastml.dir/tree.c.o
.PHONY : tree.c.o

tree.i: tree.c.i

.PHONY : tree.i

# target to preprocess a source file
tree.c.i:
	$(MAKE) -f CMakeFiles/pastml.dir/build.make CMakeFiles/pastml.dir/tree.c.i
.PHONY : tree.c.i

tree.s: tree.c.s

.PHONY : tree.s

# target to generate assembly for a file
tree.c.s:
	$(MAKE) -f CMakeFiles/pastml.dir/build.make CMakeFiles/pastml.dir/tree.c.s
.PHONY : tree.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... pastml"
	@echo "... likelihood.o"
	@echo "... likelihood.i"
	@echo "... likelihood.s"
	@echo "... logger.o"
	@echo "... logger.i"
	@echo "... logger.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... marginal_approximation.o"
	@echo "... marginal_approximation.i"
	@echo "... marginal_approximation.s"
	@echo "... marginal_likelihood.o"
	@echo "... marginal_likelihood.i"
	@echo "... marginal_likelihood.s"
	@echo "... param_minimization.o"
	@echo "... param_minimization.i"
	@echo "... param_minimization.s"
	@echo "... parsimony.o"
	@echo "... parsimony.i"
	@echo "... parsimony.s"
	@echo "... runpastml.o"
	@echo "... runpastml.i"
	@echo "... runpastml.s"
	@echo "... scaling.o"
	@echo "... scaling.i"
	@echo "... scaling.s"
	@echo "... states.o"
	@echo "... states.i"
	@echo "... states.s"
	@echo "... tree.o"
	@echo "... tree.i"
	@echo "... tree.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

